[package]
name = "smokey"
version = "0.1.0"
authors = ["Jordan Adams <hi@jordanadams.co.uk>"]

[dependencies]
serde = "0.9.6"
serde_derive = "0.9"
serde_yaml = "0.6.0"
clap = "2.20.3"
reqwest = "0.4.0"
